# EDA and formatting

After playing in Tableau, decided that needed a specific format for this.

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from collections import Counter

### Read in all the dataframes needed

In [2]:
df_netflix = pd.read_csv('../data/df_netflix.csv')
df_hulu = pd.read_csv('../data/df_hulu.csv')
df_prime = pd.read_csv('../data/df_prime.csv')
df_disney = pd.read_csv('../data/df_disney.csv')
df_hbomax = pd.read_csv('../data/df_hbomax.csv')
df_final = pd.read_csv('../data/df_final.csv')

### Combine individual services into a tidy dataset.
one row per combination of title and service (available on)

In [3]:
list_service_dfs = [df_hulu,df_netflix,df_prime,df_disney,df_hbomax]
list_services = ['Hulu', 'Netflix', 'Prime Video', 'Disney+', 'HBO Max']

In [4]:
def available_column(df, name):
    df = df.drop(df.columns[6], axis = 1)
    df['available_on'] = name
    return df

In [5]:
df_hulu = available_column(df_hulu, 'Hulu')
df_hulu.head()

,title,tv,year,rating,score_imdb,score_rotten,link,available_on
0,The Dark Knight,NaN,2008,13+,9.0,94%,https://reelgood.com/movie/the-dark-knight-2008,Hulu
1,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,Hulu
2,Parasite,NaN,2019,18+,8.6,99%,https://reelgood.com/movie/parasite-2019,Hulu
3,GoodFellas,NaN,1990,18+,8.7,96%,https://reelgood.com/movie/goodfellas-1990,Hulu
4,The Green Mile,NaN,1999,18+,8.6,78%,https://reelgood.com/movie/the-green-mile-1999,Hulu

In [6]:
for i in range(0,5):
    list_service_dfs[i] = available_column(list_service_dfs[i], list_services[i])

In [7]:
list_service_dfs[4]

,title,tv,year,rating,score_imdb,score_rotten,link,available_on
0,Game of Thrones,TV,2011,18+,9.3,89%,https://reelgood.com/show/game-of-thrones-2011,HBO Max
1,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,HBO Max
2,The Lord of the Rings: The Fellowship of the Ring,NaN,2001,13+,8.8,91%,https://reelgood.com/movie/the-lord-of-the-rin...,HBO Max
3,Fight Club,NaN,1999,18+,8.8,79%,https://reelgood.com/movie/fight-club-1999,HBO Max
4,The Lord of the Rings: The Two Towers,NaN,2002,13+,8.7,95%,https://reelgood.com/movie/the-lord-of-the-rin...,HBO Max
...,...,...,...,...,...,...,...,...
2011,What Animals See,NaN,2018,NaN,NaN,NaN,https://reelgood.com/movie/what-animals-see-2018,HBO Max
2012,The Moon's Spell On The Great Barrier Reef,NaN,2014,NaN,NaN,NaN,https://reelgood.com/movie/the-moons-spell-on-...,HBO Max
2013,Mandrake Telefilm: Part 1,NaN,2013,NaN,NaN,NaN,https://reelgood.com/movie/mandrake-telefilm-p...,HBO Max
2014,The Hunt for the Slave Ship Guerrero,NaN,2018,NaN,NaN,NaN,https://reelgood.com/movie/the-hunt-for-the-sl...,HBO Max
2015,The Rise & Fall Of T-Rex,NaN,2015,NaN,NaN,NaN,https://reelgood.com/movie/the-rise-fall-of-tr...,HBO Max

In [8]:
df_combined = pd.concat(list_service_dfs)

In [9]:
df_combined.head()

,title,tv,year,rating,score_imdb,score_rotten,link,available_on
0,The Dark Knight,NaN,2008,13+,9.0,94%,https://reelgood.com/movie/the-dark-knight-2008,Hulu
1,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,Hulu
2,Parasite,NaN,2019,18+,8.6,99%,https://reelgood.com/movie/parasite-2019,Hulu
3,GoodFellas,NaN,1990,18+,8.7,96%,https://reelgood.com/movie/goodfellas-1990,Hulu
4,The Green Mile,NaN,1999,18+,8.6,78%,https://reelgood.com/movie/the-green-mile-1999,Hulu

In [10]:
df_combined.tv = df_combined.tv.fillna('Movie')

In [11]:
df_combined.head()

,title,tv,year,rating,score_imdb,score_rotten,link,available_on
0,The Dark Knight,Movie,2008,13+,9.0,94%,https://reelgood.com/movie/the-dark-knight-2008,Hulu
1,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,Hulu
2,Parasite,Movie,2019,18+,8.6,99%,https://reelgood.com/movie/parasite-2019,Hulu
3,GoodFellas,Movie,1990,18+,8.7,96%,https://reelgood.com/movie/goodfellas-1990,Hulu
4,The Green Mile,Movie,1999,18+,8.6,78%,https://reelgood.com/movie/the-green-mile-1999,Hulu

In [12]:
df_combined.dtypes

title            object
tv               object
year              int64
rating           object
score_imdb      float64
score_rotten     object
link             object
available_on     object
dtype: object

In [13]:
#save for our records
df_combined.to_csv('../data/df_combined.csv')

## Bring in genre and country data

by combining with df_final

In [14]:
df_final.head()

,Unnamed: 0,title,tv,year,rating,score_imdb,score_rotten,netflix,Hulu,Prime Video,Disney+,HBO Max,link,genres,country
0,0,Breaking Bad,TV,2008,18+,9.5,96%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/breaking-bad-2008,"Crime, Drama, Thriller",America
1,1,Inception,NaN,2010,13+,8.8,87%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/movie/inception-2010,"Action & Adventure, Mystery, Science-Fiction, ...",United Kingdom
2,2,Back to the Future,NaN,1985,7+,8.5,96%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/movie/back-to-the-future-...,"Comedy, Fantasy, Science-Fiction, Action & Adv...",America
3,3,The Matrix,NaN,1999,18+,8.7,88%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/movie/the-matrix-1999,"Action & Adventure, Science-Fiction",Australia
4,4,Stranger Things,TV,2016,16+,8.8,93%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/stranger-things-2016,"Drama, Fantasy, Horror, Mystery, Science-Ficti...",America

In [3]:
df_details = df_final.drop(df_final.columns[:12], axis = 1)
df_details.head()

,link,genres,country
0,https://reelgood.com/show/breaking-bad-2008,"Crime, Drama, Thriller",America
1,https://reelgood.com/movie/inception-2010,"Action & Adventure, Mystery, Science-Fiction, ...",United Kingdom
2,https://reelgood.com/movie/back-to-the-future-...,"Comedy, Fantasy, Science-Fiction, Action & Adv...",America
3,https://reelgood.com/movie/the-matrix-1999,"Action & Adventure, Science-Fiction",Australia
4,https://reelgood.com/show/stranger-things-2016,"Drama, Fantasy, Horror, Mystery, Science-Ficti...",America

In [23]:
df_all_data = pd.merge(df_combined,df_details,how = 'inner', on = 'link').reset_index(drop=True)

In [24]:
df_all_data.head()

,title,tv,year,rating,score_imdb,score_rotten,link,available_on,genres,country
0,The Dark Knight,Movie,2008,13+,9.0,94%,https://reelgood.com/movie/the-dark-knight-2008,Hulu,"Action & Adventure, Crime, Drama, Thriller, My...",United Kingdom
1,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,Hulu,"Animation, Comedy, Science-Fiction, Action & A...",America
2,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,HBO Max,"Animation, Comedy, Science-Fiction, Action & A...",America
3,Parasite,Movie,2019,18+,8.6,99%,https://reelgood.com/movie/parasite-2019,Hulu,"Drama, Thriller, Comedy, Mystery, Action & Adv...",South Korea
4,GoodFellas,Movie,1990,18+,8.7,96%,https://reelgood.com/movie/goodfellas-1990,Hulu,"Biography, Crime, Drama",America

In [27]:
print(df_combined.shape)
print(df_details.shape)
print(df_all_data.shape)

(26897, 8)
(25818, 3)
(26897, 10)

In [28]:
df_all_data['decade'] = (df_all_data.year//10)*10

In [29]:
df_all_data.head()

,title,tv,year,rating,score_imdb,score_rotten,link,available_on,genres,country,decade
0,The Dark Knight,Movie,2008,13+,9.0,94%,https://reelgood.com/movie/the-dark-knight-2008,Hulu,"Action & Adventure, Crime, Drama, Thriller, My...",United Kingdom,2000
1,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,Hulu,"Animation, Comedy, Science-Fiction, Action & A...",America,2010
2,Rick and Morty,TV,2013,18+,9.2,94%,https://reelgood.com/show/rick-and-morty-2013,HBO Max,"Animation, Comedy, Science-Fiction, Action & A...",America,2010
3,Parasite,Movie,2019,18+,8.6,99%,https://reelgood.com/movie/parasite-2019,Hulu,"Drama, Thriller, Comedy, Mystery, Action & Adv...",South Korea,2010
4,GoodFellas,Movie,1990,18+,8.7,96%,https://reelgood.com/movie/goodfellas-1990,Hulu,"Biography, Crime, Drama",America,1990

In [31]:
df_all_data.to_csv('../data/df_all_data.csv', index=False)

### What are all the unique genres?

In [32]:
df_details['genres'].head()

0                               Crime, Drama, Thriller
1    Action & Adventure, Mystery, Science-Fiction, ...
2    Comedy, Fantasy, Science-Fiction, Action & Adv...
3                  Action & Adventure, Science-Fiction
4    Drama, Fantasy, Horror, Mystery, Science-Ficti...
Name: genres, dtype: object

In [53]:
df_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25818 entries, 0 to 25817
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   link     25818 non-null  object
 1   genres   10300 non-null  object
 2   country  10347 non-null  object
dtypes: object(3)
memory usage: 605.2+ KB

In [48]:
list_genres = []
for item in df_details['genres']:
    try:
        list_genres.extend(item.split(sep = ','))
    except:
        continue

In [49]:
list_genres

['Crime',
 ' Drama',
 ' Thriller',
 'Action & Adventure',
 ' Mystery',
 ' Science-Fiction',
 ' Thriller',
 'Comedy',
 ' Fantasy',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Romance',
 ' Family',
 ' Drama',
 'Action & Adventure',
 ' Science-Fiction',
 'Drama',
 ' Fantasy',
 ' Horror',
 ' Mystery',
 ' Science-Fiction',
 ' Thriller',
 ' Action & Adventure',
 'Drama',
 ' Mystery',
 ' Thriller',
 ' Crime',
 ' Horror',
 'Action & Adventure',
 ' Fantasy',
 ' Science-Fiction',
 'Drama',
 'Biography',
 ' Drama',
 'Action & Adventure',
 ' Animation',
 ' Science-Fiction',
 ' Comedy',
 ' Family',
 'Action & Adventure',
 'Action & Adventure',
 ' Animation',
 ' Family',
 ' Fantasy',
 ' Mystery',
 'Action & Adventure',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Crime',
 ' Drama',
 'Action & Adventure',
 ' Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Thriller',
 ' Action & Adventure',
 ' Crime',
 ' Mystery',
 ' Drama',
 'Comedy',
 ' Drama',
 'Drama',
 ' Fantasy',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Science-Fiction',
 ' Thriller',
 ' Fantasy',
 'Drama',
 ' Thriller',
 ' Mystery',
 ' Horror',
 'Action & Adventure',
 ' Cult',
 ' Comedy',
 ' Fantasy',
 'Action & Adventure',
 'Drama',
 ' Fantasy',
 ' Horror',
 ' Mystery',
 ' Science-Fiction',
 ' Thriller',
 'Romance',
 ' Cult',
 ' Comedy',
 ' Fantasy',
 ' Drama',
 'Drama',
 ' Science-Fiction',
 ' Fantasy',
 ' Thriller',
 ' Mystery',
 'Action & Adventure',
 ' Anime',
 ' Animation',
 ' Drama',
 ' Fantasy',
 ' Horror',
 ' Mystery',
 ' Science-Fiction',
 'Action & Adventure',
 ' Drama',
 ' Thriller',
 ' Science-Fiction',
 ' Mystery',
 ' Fantasy',
 'Drama',
 ' Romance',
 ' Science-Fiction',
 'Crime',
 ' Drama',
 'Drama',
 'Biography',
 ' LGBTQ',
 ' Drama',
 ' History',
 'Comedy',
 ' Cult',
 ' Documentary',
 'Biography',
 ' Drama',
 'Drama',
 ' Horror',
 ' Thriller',
 ' Action & Adventure',
 ' Fantasy',
 ' Science-Fiction',
 'Drama',
 ' LGBTQ',
 ' Romance',
 ' Crime',
 ' Science-Fiction',
 'Drama',
 ' Science-Fiction',
 ' Mystery',
 ' Thriller',
 'Science-Fiction',
 ' Action & Adventure',
 ' Thriller',
 ' Fantasy',
 ' Drama',
 ' Mystery',
 'Crime',
 ' Drama',
 ' Biography',
 ' Thriller',
 ' Action & Adventure',
 'Comedy',
 ' Drama',
 ' Romance',
 'Comedy',
 'Crime',
 ' Drama',
 ' Thriller',
 'Drama',
 ' Crime',
 ' Biography',
 ' Mystery',
 ' Thriller',
 ' History',
 'Crime',
 ' Drama',
 ' Thriller',
 ' Mystery',
 'Action & Adventure',
 ' Crime',
 ' Drama',
 ' Fantasy',
 ' Science-Fiction',
 ' Thriller',
 ' Mystery',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Comedy',
 'Drama',
 'Action & Adventure',
 ' Anime',
 ' Animation',
 ' Drama',
 ' Fantasy',
 ' Comedy',
 ' Science-Fiction',
 ' Mystery',
 'Action & Adventure',
 ' Biography',
 ' Drama',
 ' Sport',
 'Drama',
 ' Horror',
 ' Mystery',
 ' Crime',
 ' Thriller',
 ' Fantasy',
 ' Romance',
 'Drama',
 ' Comedy',
 ' Romance',
 'Animation',
 ' Action & Adventure',
 ' Comedy',
 ' Family',
 ' Science-Fiction',
 'Action & Adventure',
 ' Horror',
 ' Thriller',
 ' Mystery',
 'Action & Adventure',
 ' Mystery',
 ' Science-Fiction',
 ' Crime',
 ' Thriller',
 'Animation',
 ' Anime',
 ' Action & Adventure',
 ' Comedy',
 ' Fantasy',
 ' Science-Fiction',
 'Drama',
 ' Action & Adventure',
 ' Fantasy',
 ' Horror',
 ' Mystery',
 'Drama',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Mystery',
 ' Fantasy',
 ' Thriller',
 'Action & Adventure',
 ' Children',
 ' Science-Fiction',
 ' Family',
 ' Fantasy',
 'Animation',
 ' Family',
 ' Fantasy',
 ' Action & Adventure',
 ' Comedy',
 'Comedy',
 'Drama',
 ' Family',
 'Drama',
 ' Fantasy',
 ' Science-Fiction',
 ' Romance',
 ' History',
 ' Animation',
 ' Comedy',
 ' Action & Adventure',
 'Comedy',
 ' Drama',
 ' Fantasy',
 ' Romance',
 ' Science-Fiction',
 'Animation',
 ' Comedy',
 ' Family',
 ' Fantasy',
 'Thriller',
 ' Crime',
 ' Drama',
 ' Mystery',
 ' Action & Adventure',
 'Comedy',
 ' Drama',
 'Drama',
 ' Sport',
 ' Crime',
 'Crime',
 ' Thriller',
 ' Mystery',
 ' Documentary',
 ' Action & Adventure',
 'Horror',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Action & Adventure',
 ' History',
 ' Romance',
 ' Drama',
 'Family',
 ' Fantasy',
 ' Musical',
 ' Comedy',
 'Comedy',
 ' Drama',
 'Comedy',
 ' Fantasy',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Family',
 'Action & Adventure',
 ' Drama',
 ' Fantasy',
 ' Science-Fiction',
 ' Thriller',
 'Action & Adventure',
 ' Biography',
 ' Drama',
 ' History',
 ' Fantasy',
 'Drama',
 ' Action & Adventure',
 ' Fantasy',
 ' Science-Fiction',
 ' Crime',
 'Fantasy',
 ' Crime',
 ' Science-Fiction',
 ' Drama',
 ' Comedy',
 'Thriller',
 ' Biography',
 ' Drama',
 ' History',
 'Action & Adventure',
 ' Drama',
 ' Science-Fiction',
 'Comedy',
 ' Drama',
 ' Romance',
 ' Mystery',
 ' Thriller',
 'Drama',
 ' Biography',
 ' Romance',
 'Action & Adventure',
 ' Comedy',
 ' Fantasy',
 ' Romance',
 'Drama',
 ' LGBTQ',
 ' Comedy',
 ' Musical',
 'Action & Adventure',
 'Drama',
 ' Romance',
 'Documentary',
 ' Biography',
 ' Sport',
 'Documentary',
 ' Crime',
 ' History',
 'Biography',
 ' Drama',
 ' Documentary',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Comedy',
 ' Drama',
 ' Mystery',
 ' Crime',
 ' Thriller',
 'Drama',
 ' Fantasy',
 ' Romance',
 ' Mystery',
 ' Thriller',
 'Comedy',
 ' Drama',
 ' Mystery',
 ' Crime',
 'Comedy',
 'Action & Adventure',
 ' Comedy',
 ' Crime',
 ' Drama',
 ' Romance',
 ' Thriller',
 'Comedy',
 ' LGBTQ',
 ' Crime',
 ' Drama',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Drama',
 ' History',
 'Comedy',
 ' Drama',
 'Drama',
 ' Fantasy',
 ' Horror',
 ' Romance',
 ' Mystery',
 ' Thriller',
 ' Science-Fiction',
 'Drama',
 ' Thriller',
 ' Crime',
 ' Mystery',
 'Animation',
 ' Anime',
 ' Drama',
 ' Romance',
 ' Family',
 'Action & Adventure',
 ' Fantasy',
 ' Comedy',
 ' Science-Fiction',
 'Animation',
 ' Family',
 ' Fantasy',
 ' Action & Adventure',
 ' Drama',
 'Documentary',
 ' Drama',
 'Comedy',
 ' Fantasy',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Romance',
 ' Family',
 'Action & Adventure',
 ' Drama',
 ' Family',
 ' Fantasy',
 ' Mystery',
 ' Romance',
 'Documentary',
 ' Biography',
 ' Musical',
 'Comedy',
 ' Drama',
 ' Romance',
 'Crime',
 ' Drama',
 ' Thriller',
 ' Action & Adventure',
 ' Mystery',
 'Biography',
 ' Drama',
 ' Crime',
 'Horror',
 ' Thriller',
 ' Drama',
 ' Fantasy',
 'Animation',
 ' Comedy',
 ' Drama',
 'Comedy',
 ' Romance',
 'Drama',
 ' Action & Adventure',
 ' Crime',
 ' Thriller',
 'Drama',
 ' LGBTQ',
 ' Mystery',
 ' Science-Fiction',
 ' Thriller',
 ' Fantasy',
 'Biography',
 ' Comedy',
 ' Drama',
 'Horror',
 ' Cult',
 'Drama',
 ' Action & Adventure',
 ' Fantasy',
 ' Crime',
 ' Mystery',
 ' Science-Fiction',
 'Comedy',
 ' Drama',
 'Drama',
 ' Fantasy',
 ' Romance',
 ' Comedy',
 ' Science-Fiction',
 'Biography',
 ' Drama',
 ' Crime',
 'Crime',
 ' Drama',
 ' Thriller',
 ' Action & Adventure',
 ' Mystery',
 'Action & Adventure',
 ' Comedy',
 ' Crime',
 ' Fantasy',
 'Comedy',
 ' Romance',
 ' Drama',
 'Biography',
 ' Drama',
 ' History',
 ' Romance',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Drama',
 ' Romance',
 'Comedy',
 'Action & Adventure',
 ' LGBTQ',
 ' Comedy',
 ' Drama',
 ' Romance',
 'Fantasy',
 ' Science-Fiction',
 ' Drama',
 ' Horror',
 ' Mystery',
 ' Thriller',
 'Action & Adventure',
 ' Drama',
 ' Science-Fiction',
 ' Mystery',
 ' Fantasy',
 'Comedy',
 ' Horror',
 'Action & Adventure',
 ' Drama',
 ' History',
 'Comedy',
 ' Drama',
 'Action & Adventure',
 ' Science-Fiction',
 ' Mystery',
 ' Thriller',
 'Crime',
 ' Thriller',
 ' Drama',
 ' Comedy',
 ' Mystery',
 'Drama',
 ' LGBTQ',
 ' Romance',
 'Crime',
 ' Drama',
 ' Romance',
 ' Thriller',
 'Drama',
 ' Stand-up & Talk',
 ' Comedy',
 ' Biography',
 ' History',
 'Crime',
 ' Drama',
 ' Thriller',
 ' Mystery',
 'Mystery',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Drama',
 ' Thriller',
 ' Fantasy',
 'Drama',
 ' Biography',
 ' Comedy',
 ' History',
 'Drama',
 'Drama',
 'Action & Adventure',
 ' History',
 ' Drama',
 'Drama',
 ' Crime',
 ' Thriller',
 ' Mystery',
 'Crime',
 ' Drama',
 ' Mystery',
 'Animation',
 ' Action & Adventure',
 ' Family',
 ' Romance',
 ' Drama',
 'Action & Adventure',
 ' Drama',
 ' Musical',
 ' Romance',
 'Drama',
 'Action & Adventure',
 ' Crime',
 ' Drama',
 ' Science-Fiction',
 ' Thriller',
 ' Fantasy',
 'Documentary',
 ' Thriller',
 ' Sport',
 'Animation',
 ' Science-Fiction',
 ' Comedy',
 ' Fantasy',
 ' Horror',
 'Action & Adventure',
 ' LGBTQ',
 ' Comedy',
 ' Drama',
 ' Fantasy',
 ' Science-Fiction',
 ' Mystery',
 'Documentary',
 ' Biography',
 ' Sport',
 ' Action & Adventure',
 'Biography',
 ' Comedy',
 ' Drama',
 ' Musical',
 ' History',
 'Animation',
 ' Anime',
 ' Crime',
 ' Fantasy',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Thriller',
 ' Crime',
 ' Drama',
 ' Action & Adventure',
 'Action & Adventure',
 ' Drama',
 ' Science-Fiction',
 'Action & Adventure',
 ' Crime',
 ' Drama',
 ' Science-Fiction',
 ' Thriller',
 'Comedy',
 ' Drama',
 ' Romance',
 ' Sport',
 'Action & Adventure',
 ' Drama',
 ' Horror',
 ' Thriller',
 ' Mystery',
 ' Science-Fiction',
 ' Fantasy',
 ' History',
 'Comedy',
 'Crime',
 ' Drama',
 ' Thriller',
 ' Mystery',
 'Drama',
 ' Science-Fiction',
 ' Horror',
 ' Thriller',
 ' Mystery',
 'Comedy',
 ' Romance',
 'Drama',
 'Action & Adventure',
 ' Thriller',
 ' Mystery',
 ' Science-Fiction',
 ' Documentary',
 'Comedy',
 ' Drama',
 ' History',
 'Action & Adventure',
 ' Biography',
 ' Drama',
 ' History',
 ' Sport',
 'Drama',
 ' Fantasy',
 ' Action & Adventure',
 ' Romance',
 ' Science-Fiction',
 'Comedy',
 ' Drama',
 ' Romance',
 'Drama',
 'Documentary',
 ' Biography',
 ' Musical',
 'Documentary',
 ' Crime',
 'Comedy',
 ' Drama',
 ' Romance',
 ' Science-Fiction',
 ' Thriller',
 ' Mystery',
 'Crime',
 ' Drama',
 ' Horror',
 ' Mystery',
 ' Thriller',
 'Drama',
 ' Crime',
 ' Thriller',
 'Musical',
 ' Crime',
 ' Drama',
 ' Romance',
 'Drama',
 ' Romance',
 'Action & Adventure',
 ' Drama',
 'Family',
 ' Animation',
 ' Action & Adventure',
 ' Comedy',
 ' Fantasy',
 ' Drama',
 ' Mystery',
 ' Thriller',
 'Comedy',
 ' Horror',
 ' Action & Adventure',
 ' Fantasy',
 ' Thriller',
 'Animation',
 ' Action & Adventure',
 ' Drama',
 ' Family',
 ' Fantasy',
 'Drama',
 ' Horror',
 ' Thriller',
 ' Fantasy',
 ' Mystery',
 ' Science-Fiction',
 'Crime',
 ' Horror',
 ' Thriller',
 ' Mystery',
 ' Musical',
 'Drama',
 ' Crime',
 ' Mystery',
 ' Romance',
 ' Thriller',
 'Comedy',
 ' Drama',
 ' Romance',
 'Comedy',
 ' Drama',
 ' Musical',
 ' Mystery',
 ' Romance',
 'Comedy',
 ' Drama',
 ' Fantasy',
 ' Musical',
 'Drama',
 'Action & Adventure',
 ' Crime',
 ' Drama',
 'Drama',
 ' Mystery',
 ' Thriller',
 'Comedy',
 ' Drama',
 ' Mystery',
 ' Fantasy',
 'Action & Adventure',
 ' Thriller',
 ' Drama',
 ' Mystery',
 'Drama',
 ' Mystery',
 'Animation',
 ' Comedy',
 ' Romance',
 'Animation',
 ' Action & Adventure',
 ' Comedy',
 ' Drama',
 ' Family',
 'Action & Adventure',
 ' Drama',
 ' History',
 ' Thriller',
 ' Mystery',
 ' Crime',
 'Action & Adventure',
 ' Science-Fiction',
 ' Thriller',
 ' Mystery',
 ' Fantasy',
 ' Horror',
 'Comedy',
 ' LGBTQ',
 ' Drama',
 ' Romance',
 'Documentary',
 ' LGBTQ',
 ' Crime',
 'Drama',
 ' LGBTQ',
 ' Romance',
 'Documentary',
 'Horror',
 ' Cult',
 ' Mystery',
 ' Thriller',
 'Drama',
 ' Action & Adventure',
 ' Crime',
 ' Thriller',
 ' Fantasy',
 ' Science-Fiction',
 'Animation',
 ' Family',
 ' Fantasy',
 ' Action & Adventure',
 ' Comedy',
 ' Musical',
 ' Romance',
 'Mystery',
 ' Thriller',
 ' Drama',
 ' Documentary',
 'Comedy',
 ' Crime',
 ' Drama',
 ' Thriller',
 'Crime',
 ' Drama',
 ' Mystery',
 ' Thriller',
 ' Horror',
 'Action & Adventure',
 ' Comedy',
 ' Drama',
 ' Travel',
 ' Romance',
 'Animation',
 ' Anime',
 ' Action & Adventure',
 ' Drama',
 ' Fantasy',
 ' Science-Fiction',
 'Biography',
 ' Crime',
 ' Drama',
 'Action & Adventure',
 ' Science-Fiction',
 ' Drama',
 ' Fantasy',
 'Comedy',
 ' LGBTQ',
 ' Romance',
 ' Drama',
 'Action & Adventure',
 ' Drama',
 ' Science-Fiction',
 ' Fantasy',
 'Comedy',
 ' Romance',
 ' Drama',
 'Comedy',
 ' Independent',
 ' Drama',
 'Horror',
 ' Cult',
 ' Comedy',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Fantasy',
 'Biography',
 ' Drama',
 ' History',
 'Animation',
 ' Comedy',
 ' Family',
 ' Food',
 ' Action & Adventure',
 ' Fantasy',
 ' Science-Fiction',
 'Drama',
 ' History',
 ' Biography',
 'Action & Adventure',
 ' Drama',
 ' History',
 'Animation',
 ' Action & Adventure',
 ' Fantasy',
 ' Horror',
 'Comedy',
 ' Drama',
 ' Romance',
 'Drama',
 ' Fantasy',
 ' Mystery',
 ' Science-Fiction',
 'Thriller',
 ' Action & Adventure',
 ' Drama',
 ' Crime',
 'Crime',
 ' Independent',
 ' Drama',
 ' Thriller',
 ' Mystery',
 'Animation',
 ' Action & Adventure',
 ' Comedy',
 ' Family',
 ' Fantasy',
 'Action & Adventure',
 ' Fantasy',
 ' Science-Fiction',
 ' Drama',
 'Drama',
 ' Mystery',
 ' Thriller',
 'Drama',
 ' Family',
 'Documentary',
 ' Drama',
 ' History',
 'Drama',
 ' Crime',
 'Documentary',
 ' History',
 'Biography',
 ' Drama',
 ' History',
 'Action & Adventure',
 ' Science-Fiction',
 ' Thriller',
 ' Mystery',
 'Comedy',
 ' Drama',
 'Action & Adventure',
 ' Drama',
 ' Fantasy',
 ' Horror',
 ' Mystery',
 ' Thriller',
 ' Science-Fiction',
 'Drama',
 'Horror',
 ' Thriller',
 ' Drama',
 'Action & Adventure',
 ' Comedy',
 ' Drama',
 ' Romance',
 'Horror',
 ' Mystery',
 ' Drama',
 'Thriller',
 ' Crime',
 ' Mystery',
 ' Drama',
 'Action & Adventure',
 ' Comedy',
 ' Drama',
 ' Fantasy',
 ' Science-Fiction',
 'Drama',
 ' Action & Adventure',
 'Drama',
 ' Science-Fiction',
 ' Action & Adventure',
 ' Crime',
 ' Horror',
 ' Comedy',
 ' Fantasy',
 'Action & Adventure',
 ' Anime',
 ' Drama',
 ' Science-Fiction',
 ' Animation',
 ' Thriller',
 ' Fantasy',
 'Comedy',
 ' Crime',
 ' Drama',
 'Comedy',
 'Drama',
 'Biography',
 ' Drama',
 ' History',
 ' Sport',
 'Crime',
 ' Documentary',
 'Biography',
 ' Drama',
 ' Mystery',
 ' Thriller',
 ' Comedy',
 ...]

In [51]:
len(list_genres)

33483

In [54]:
Counter(list_genres)

Counter({'Crime': 529,
         ' Drama': 3399,
         ' Thriller': 2504,
         'Action & Adventure': 2060,
         ' Mystery': 2555,
         ' Science-Fiction': 1506,
         'Comedy': 1800,
         ' Fantasy': 1492,
         ' Action & Adventure': 1340,
         ' Romance': 1786,
         ' Family': 1372,
         'Drama': 2240,
         ' Horror': 923,
         ' Crime': 1101,
         'Biography': 225,
         ' Animation': 274,
         ' Comedy': 1584,
         'Thriller': 255,
         ' Cult': 127,
         'Romance': 90,
         ' Anime': 294,
         ' LGBTQ': 188,
         ' History': 599,
         ' Documentary': 214,
         'Science-Fiction': 110,
         ' Biography': 315,
         ' Sport': 351,
         'Animation': 769,
         ' Children': 213,
         'Horror': 734,
         'Family': 131,
         ' Musical': 661,
         'Fantasy': 78,
         'Documentary': 980,
         ' Stand-up & Talk': 42,
         'Mystery': 79,
         'Musical': 35,
         ' Travel': 23,
         ' Independent': 189,
         ' Food': 20,
         ' Reality': 78,
         'History': 15,
         'Reality': 68,
         ' Game Show': 32,
         'Game Show': 20,
         'Children': 63,
         'Sport': 13,
         ' Home & Garden': 1,
         'Anime': 2,
         'LGBTQ': 1,
         'Food': 2,
         'Independent': 1})

#### We can see there is some repetition here. Appears to be due to spaces
trying this again, with stripping spaces

In [61]:
list_genres2 = []
for item in df_details['genres']:
    try:
        list_genres2.extend(item.split(sep = ','))
    except:
        continue

In [63]:
list_genres2 = [x.strip(' ') for x in list_genres2]

In [65]:
Counter(list_genres2)

Counter({'Crime': 1630,
         'Drama': 5639,
         'Thriller': 2759,
         'Action & Adventure': 3400,
         'Mystery': 2634,
         'Science-Fiction': 1616,
         'Comedy': 3384,
         'Fantasy': 1570,
         'Romance': 1876,
         'Family': 1503,
         'Horror': 1657,
         'Biography': 540,
         'Animation': 1043,
         'Cult': 127,
         'Anime': 296,
         'LGBTQ': 189,
         'History': 614,
         'Documentary': 1194,
         'Sport': 364,
         'Children': 276,
         'Musical': 696,
         'Stand-up & Talk': 42,
         'Travel': 23,
         'Independent': 190,
         'Food': 22,
         'Reality': 146,
         'Game Show': 52,
         'Home & Garden': 1})

In [81]:
data = {'genres': list(Counter(list_genres2).keys()),
        'count': list(Counter(list_genres2).values())}


df_genre_counts = pd.DataFrame(data, columns = ['genres', 'count'])

In [86]:
df_genre_counts = df_genre_counts.sort_values(by = 'genres').reset_index(drop=True)

In [87]:
df_genre_counts

                genres  count
0   Action & Adventure   3400
1            Animation   1043
2                Anime    296
3            Biography    540
4             Children    276
5               Comedy   3384
6                Crime   1630
7                 Cult    127
8          Documentary   1194
9                Drama   5639
10              Family   1503
11             Fantasy   1570
12                Food     22
13           Game Show     52
14             History    614
15       Home & Garden      1
16              Horror   1657
17         Independent    190
18               LGBTQ    189
19             Musical    696
20             Mystery   2634
21             Reality    146
22             Romance   1876
23     Science-Fiction   1616
24               Sport    364
25     Stand-up & Talk     42
26            Thriller   2759
27              Travel     23

In [89]:
df_genre_counts.to_csv('../data/df_genre_counts.csv', index = False)

In [4]:
list_countries = list(df_details.country)
len(list_countries)

25818

In [6]:
Counter(list_countries)

Counter({'America': 5637,
         'United Kingdom': 931,
         'Australia': 224,
         'Germany': 211,
         'France': 343,
         'Spain': 98,
         'India': 355,
         'Mexico': 42,
         'Canada': 615,
         nan: 15471,
         'Japan': 466,
         'South Korea': 136,
         'Hong Kong': 125,
         'Czechia': 24,
         'Belgium': 86,
         'Finland': 13,
         'China': 90,
         'Austria': 25,
         'Italy': 148,
         'Thailand': 25,
         'Brazil': 34,
         'Israel': 21,
         'Egypt': 13,
         'Ireland': 59,
         'Ukraine': 4,
         'United Arab Emirates': 8,
         'Hungary': 12,
         'Indonesia': 18,
         'Iran': 5,
         'Denmark': 59,
         'Syria': 2,
         'New Zealand': 37,
         'Romania': 20,
         'Switzerland': 17,
         'Uruguay': 1,
         'Iceland': 8,
         'Norway': 24,
         'Turkey': 19,
         'Ghana': 2,
         'Singapore': 6,
         'Russia': 25,
         'Sweden': 25,
         'Poland': 15,
         'Philippines': 41,
         'Bulgaria': 15,
         'Argentina': 50,
         'Netherlands': 20,
         'British Indian Ocean Territory': 2,
         'Colombia': 14,
         'South Africa': 30,
         'Taiwan': 38,
         'Pakistan': 6,
         'Puerto Rico': 5,
         'Portugal': 1,
         'Cambodia': 2,
         'Peru': 3,
         'Croatia': 8,
         'Nigeria': 4,
         'Chile': 10,
         'Kenya': 2,
         'Malaysia': 5,
         'Botswana': 1,
         'Vietnam': 1,
         'Macedonia': 1,
         'Tanzania': 2,
         'Iraq': 2,
         'Luxembourg': 3,
         'Venezuela': 4,
         'Latvia': 1,
         'Paraguay': 1,
         'Estonia': 1,
         'Uganda': 1,
         'Afghanistan': 2,
         'Greece': 4,
         'Jamaica': 1,
         'Belarus': 1,
         'Georgia': 1,
         'Serbia': 1,
         'Qatar': 1,
         'Guatemala': 1,
         'Ecuador': 2,
         'Morocco': 2,
         'Bangladesh': 1,
         'Bosnia and Herzegovina': 1,
         'Ethiopia': 1,
         'Algeria': 4,
         'Virgin Islands (U.S.)': 1,
         'Mongolia': 1,
         'Mozambique': 1,
         'Albania': 1,
         'Rwanda': 1,
         'Lithuania': 1,
         'Palestine': 1,
         'Mali': 1,
         'Trinidad and Tobago': 2,
         'Liberia': 1,
         'Azerbaijan': 1,
         'Equatorial Guinea': 1,
         'Cuba': 3,
         'Lebanon': 1,
         'Cyprus': 1,
         'Fiji': 1,
         'Dominican Republic': 1,
         'Bahamas': 1,
         'Bolivia': 1})

In [8]:
data_country = {'country': list(Counter(list_countries).keys()),
                'count': list(Counter(list_countries).values())}
df_country_counts = pd.DataFrame(data_country,columns = ['country','count'])

In [11]:
list(df_country_counts.sort_values(by = 'country').country)

['Afghanistan',
 'Albania',
 'Algeria',
 'America',
 'Argentina',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Indian Ocean Territory',
 'Bulgaria',
 'Cambodia',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'Equatorial Guinea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Kenya',
 'Latvia',
 'Lebanon',
 'Liberia',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Malaysia',
 'Mali',
 'Mexico',
 'Mongolia',
 'Morocco',
 'Mozambique',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Norway',
 'Pakistan',
 'Palestine',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Serbia',
 'Singapore',
 'South Africa',
 'South Korea',
 'Spain',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tanzania',
 'Thailand',
 'Trinidad and Tobago',
 'Turkey',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'Uruguay',
 'Venezuela',
 'Vietnam',
 'Virgin Islands (U.S.)',
 nan]