In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re
from functools import reduce

In [2]:
#bringing in the function written in the genre data prework notebook.

def get_genres_and_country(link):
    '''
    This function uses a link to detailed info for a title in reelgood.com to return a dictionary
    with values for genres and country
    '''
    details_soup = BeautifulSoup(requests.get(link).content, 'lxml') #get the soup out of the link
    details_section = details_soup.find_all('div',attrs={'class': 'css-1ss0qk ey4ir3j0'}) #select the section which includes the details for the title
    details_section_soup = BeautifulSoup(str(details_section),'lxml') #turn the details section into soup
    genre_section = details_section_soup.find_all('a',attrs={'href': re.compile('/(movies|tv)/genre/')}) #find the genres
    #add the text into a list
    genres = []
    
    for i in range (0,len(genre_section)): 
        genres.append(genre_section[i].text)
        genres = list(dict.fromkeys(genres)) #removing duplicates, as sometimes duplicates repeated in "more genres"
    
    genres_str = ', '.join(map(str,genres))#turn list of genres into one string
    
    #starting here, code to get the country
    country_section = details_section_soup.find_all('a', attrs={'href':re.compile('^/country/')})
    country = country_section[0].text
    return {'genres' : genres_str, 'country': country}

In [4]:
link = 'https://reelgood.com/show/modern-family-2009'

In [5]:
details_soup = BeautifulSoup(requests.get(link).content, 'lxml') #get the soup out of the link
details_section = details_soup.find_all('div',attrs={'class': 'css-1ss0qk ey4ir3j0'}) #select the section which includes the details for the title
details_section_soup = BeautifulSoup(str(details_section),'lxml') #turn the details section into soup
genre_section = details_section_soup.find_all('a',attrs={'href': re.compile('/(movies|tv)/genre/')}) #find the genres

In [6]:
genre_section

[<a class="css-jmgx9u" href="/tv/genre/comedy">Comedy<meta content="Comedy" itemprop="genre"/></a>,
 <a class="css-jmgx9u" href="/tv/genre/drama">Drama<meta content="Drama" itemprop="genre"/></a>,
 <a href="/tv/genre/comedy">Comedy</a>,
 <a href="/tv/genre/drama">Drama</a>,
 <a href="/tv/genre/romance">Romance</a>,
 <a href="/tv/genre/family">Family</a>]

In [7]:
len(genre_section)

6

In [9]:
genres = []
for i in range (0,len(genre_section)): 
    genres.append(genre_section[i].text)
    genres = list(dict.fromkeys(genres)) #removing duplicates, as sometimes duplicates repeated in "more genres"

In [10]:
genres

['Comedy', 'Drama', 'Romance', 'Family']

In [11]:
genres_str = ', '.join(map(str,genres))#turn list of genres into one string

In [12]:
genres_str

'Comedy, Drama, Romance, Family'

In [13]:
country_section = details_section_soup.find_all('a', attrs={'href':re.compile('^/country/')})
country = country_section[0].text

IndexError: list index out of range

In [18]:
details_section_soup.find_all('a', attrs={'href':re.compile('^/country/')})

[]

In [15]:
get_genres_and_country('https://reelgood.com/movie/the-good-the-bad-and-the-ugly-1966')

{'genres': '', 'country': 'Germany'}

In [19]:
def get_genres_and_country2(link):
    '''
    This function uses a link to detailed info for a title in reelgood.com to return a dictionary
    with values for genres and country
    '''
    details_soup = BeautifulSoup(requests.get(link).content, 'lxml') #get the soup out of the link
    details_section = details_soup.find_all('div',attrs={'class': 'css-1ss0qk ey4ir3j0'}) #select the section which includes the details for the title
    details_section_soup = BeautifulSoup(str(details_section),'lxml') #turn the details section into soup
    genre_section = details_section_soup.find_all('a',attrs={'href': re.compile('/(movies|tv)/genre/')}) #find the genres
    #add the text into a list
    genres = []
    country = []
    for i in range (0,len(genre_section)): 
        genres.append(genre_section[i].text)
        genres = list(dict.fromkeys(genres)) #removing duplicates, as sometimes duplicates repeated in "more genres"
    
    genres_str = ', '.join(map(str,genres))#turn list of genres into one string
    
    #starting here, code to get the country
    country_section = details_section_soup.find_all('a', attrs={'href':re.compile('^/country/')})
    if len(country_section) > 0:
        country = country_section[0].text
    else:
        country = ''
    return {'genres' : genres_str, 'country': country}

In [20]:
get_genres_and_country2(link)

{'genres': 'Comedy, Drama, Romance, Family', 'country': ''}

#### Run for all missing links

In [21]:
df_missing = pd.read_csv('../data/df_missing.csv')

In [22]:
df_missing.head()

,title,tv,year,rating,score_imdb,score_rotten,netflix,Hulu,Prime Video,Disney+,HBO Max,link,genres,country
0,The Office,TV,2005,16+,8.9,81%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-office-2005,NaN,NaN
1,Better Call Saul,TV,2015,18+,8.7,97%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/better-call-saul-2015,NaN,NaN
2,Mad Men,TV,2007,16+,8.6,94%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/mad-men-2007,NaN,NaN
3,The Blacklist,TV,2013,16+,8.0,91%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-blacklist-2013,NaN,NaN
4,The Invisible Guest,NaN,2016,18+,8.1,67%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/movie/the-invisible-guest...,NaN,NaN

In [23]:
df_missing['genres'] = ''
df_missing['country'] = ''
df_missing.head(2)

,title,tv,year,rating,score_imdb,score_rotten,netflix,Hulu,Prime Video,Disney+,HBO Max,link,genres,country
0,The Office,TV,2005,16+,8.9,81%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-office-2005,,
1,Better Call Saul,TV,2015,18+,8.7,97%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/better-call-saul-2015,,

In [27]:
%%time
#run function in our combined dataframe
for row in df_missing.itertuples():
    try:
        details = get_genres_and_country2(row.link)
        df_missing.at[row.Index,'genres'] = details['genres']
        df_missing.at[row.Index,'country'] = details['country']
    except:
        continue

Wall time: 20h 19min 26s

In [28]:
df_missing.head()

,title,tv,year,rating,score_imdb,score_rotten,netflix,Hulu,Prime Video,Disney+,HBO Max,link,genres,country
0,The Office,TV,2005,16+,8.9,81%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-office-2005,Comedy,
1,Better Call Saul,TV,2015,18+,8.7,97%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/better-call-saul-2015,"Comedy, Crime, Drama",
2,Mad Men,TV,2007,16+,8.6,94%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/mad-men-2007,Drama,
3,The Blacklist,TV,2013,16+,8.0,91%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-blacklist-2013,"Action & Adventure, Thriller, Crime, Drama, My...",
4,The Invisible Guest,NaN,2016,18+,8.1,67%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/movie/the-invisible-guest...,"Crime, Mystery, Thriller",

In [29]:
df_missing.tail()

,title,tv,year,rating,score_imdb,score_rotten,netflix,Hulu,Prime Video,Disney+,HBO Max,link,genres,country
15466,What Animals See,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/what-animals-see-2018,,
15467,The Moon's Spell On The Great Barrier Reef,NaN,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/the-moons-spell-on-...,,
15468,Mandrake Telefilm: Part 1,NaN,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/mandrake-telefilm-p...,,
15469,The Hunt for the Slave Ship Guerrero,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/the-hunt-for-the-sl...,,
15470,The Rise & Fall Of T-Rex,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/the-rise-fall-of-tr...,,

In [32]:
df_not_missing = df_missing

In [33]:
df_not_missing.to_csv('../data/df_not_missing.csv')

### Bring in the missing genres to the full dataset

In [35]:
df_all_data2 = pd.read_csv('../data/df_all_data.csv')

In [53]:
df_not_missing

,Unnamed: 0,title,tv,year,rating,score_imdb,score_rotten,netflix,Hulu,Prime Video,Disney+,HBO Max,link,genres,country
0,0,The Office,TV,2005,16+,8.9,81%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-office-2005,Comedy,NaN
1,1,Better Call Saul,TV,2015,18+,8.7,97%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/better-call-saul-2015,"Comedy, Crime, Drama",NaN
2,2,Mad Men,TV,2007,16+,8.6,94%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/mad-men-2007,Drama,NaN
3,3,The Blacklist,TV,2013,16+,8.0,91%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/show/the-blacklist-2013,"Action & Adventure, Thriller, Crime, Drama, My...",NaN
4,4,The Invisible Guest,NaN,2016,18+,8.1,67%,Yes,NaN,NaN,NaN,NaN,https://reelgood.com/movie/the-invisible-guest...,"Crime, Mystery, Thriller",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15466,15466,What Animals See,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/what-animals-see-2018,NaN,NaN
15467,15467,The Moon's Spell On The Great Barrier Reef,NaN,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/the-moons-spell-on-...,NaN,NaN
15468,15468,Mandrake Telefilm: Part 1,NaN,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/mandrake-telefilm-p...,NaN,NaN
15469,15469,The Hunt for the Slave Ship Guerrero,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/the-hunt-for-the-sl...,NaN,NaN
15470,15470,The Rise & Fall Of T-Rex,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,https://reelgood.com/movie/the-rise-fall-of-tr...,NaN,NaN

In [36]:
df_all_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26897 entries, 0 to 26896
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         26897 non-null  object
 1   tv            26897 non-null  object
 2   year          26897 non-null  int64
 3   rating        13112 non-null  object
 4   score_imdb    24921 non-null  float64
 5   score_rotten  8148 non-null   object
 6   link          26897 non-null  object
 7   available_on  26897 non-null  object
 8   genres        10866 non-null  object
 9   country       10916 non-null  object
 10  decade        26897 non-null  int64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.3+ MB

In [38]:
df_all_data2[df_all_data2.genres.isnull()].shape

(16031, 11)

In [56]:
df_not_missing[['link','genres']]

,link,genres
0,https://reelgood.com/show/the-office-2005,Comedy
1,https://reelgood.com/show/better-call-saul-2015,"Comedy, Crime, Drama"
2,https://reelgood.com/show/mad-men-2007,Drama
3,https://reelgood.com/show/the-blacklist-2013,"Action & Adventure, Thriller, Crime, Drama, My..."
4,https://reelgood.com/movie/the-invisible-guest...,"Crime, Mystery, Thriller"
...,...,...
15466,https://reelgood.com/movie/what-animals-see-2018,NaN
15467,https://reelgood.com/movie/the-moons-spell-on-...,NaN
15468,https://reelgood.com/movie/mandrake-telefilm-p...,NaN
15469,https://reelgood.com/movie/the-hunt-for-the-sl...,NaN
15470,https://reelgood.com/movie/the-rise-fall-of-tr...,NaN

In [57]:
df_all_data2 = pd.merge(df_all_data2, df_not_missing[['link','genres']], how = 'left', on = 'link')

In [58]:
df_all_data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26897 entries, 0 to 26896
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         26897 non-null  object
 1   tv            26897 non-null  object
 2   year          26897 non-null  int64
 3   rating        13112 non-null  object
 4   score_imdb    24921 non-null  float64
 5   score_rotten  8148 non-null   object
 6   link          26897 non-null  object
 7   available_on  26897 non-null  object
 8   genres_x      10866 non-null  object
 9   country       10916 non-null  object
 10  decade        26897 non-null  int64
 11  genres_y      14199 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.7+ MB

In [61]:
df_all_data2['genres'] = df_all_data2.genres_x.combine_first(df_all_data2.genres_y)

In [63]:
df_all_data2[df_all_data2.genres_x.isnull()]

,title,tv,year,rating,score_imdb,score_rotten,link,available_on,genres_x,country,decade,genres_y,genres
32,Modern Family,TV,2009,16+,8.4,85%,https://reelgood.com/show/modern-family-2009,Hulu,NaN,NaN,2000,"Comedy, Drama, Romance, Family","Comedy, Drama, Romance, Family"
84,Shoplifters,Movie,2018,18+,8.0,99%,https://reelgood.com/movie/shoplifters-2018,Hulu,NaN,NaN,2010,"Drama, Crime","Drama, Crime"
135,Mr. Bean,TV,1990,all,8.5,100%,https://reelgood.com/show/mr-bean-1990,Hulu,NaN,NaN,1990,"Comedy, Family","Comedy, Family"
136,Mr. Bean,TV,1990,all,8.5,100%,https://reelgood.com/show/mr-bean-1990,Prime Video,NaN,NaN,1990,"Comedy, Family","Comedy, Family"
150,Jiro Dreams of Sushi,Movie,2011,7+,7.9,99%,https://reelgood.com/movie/jiro-dreams-of-sush...,Hulu,NaN,NaN,2010,"Documentary, Food","Documentary, Food"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26892,What Animals See,Movie,2018,NaN,NaN,NaN,https://reelgood.com/movie/what-animals-see-2018,HBO Max,NaN,NaN,2010,NaN,NaN
26893,The Moon's Spell On The Great Barrier Reef,Movie,2014,NaN,NaN,NaN,https://reelgood.com/movie/the-moons-spell-on-...,HBO Max,NaN,NaN,2010,NaN,NaN
26894,Mandrake Telefilm: Part 1,Movie,2013,NaN,NaN,NaN,https://reelgood.com/movie/mandrake-telefilm-p...,HBO Max,NaN,NaN,2010,NaN,NaN
26895,The Hunt for the Slave Ship Guerrero,Movie,2018,NaN,NaN,NaN,https://reelgood.com/movie/the-hunt-for-the-sl...,HBO Max,NaN,NaN,2010,NaN,NaN
26896,The Rise & Fall Of T-Rex,Movie,2015,NaN,NaN,NaN,https://reelgood.com/movie/the-rise-fall-of-tr...,HBO Max,NaN,NaN,2010,NaN,NaN

In [64]:
df_all_data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26897 entries, 0 to 26896
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         26897 non-null  object
 1   tv            26897 non-null  object
 2   year          26897 non-null  int64
 3   rating        13112 non-null  object
 4   score_imdb    24921 non-null  float64
 5   score_rotten  8148 non-null   object
 6   link          26897 non-null  object
 7   available_on  26897 non-null  object
 8   genres_x      10866 non-null  object
 9   country       10916 non-null  object
 10  decade        26897 non-null  int64
 11  genres_y      14199 non-null  object
 12  genres        25065 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 2.9+ MB

In [65]:
df_all_data2 = df_all_data2.drop(columns = ['genres_x', 'genres_y'])

In [66]:
df_all_data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26897 entries, 0 to 26896
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         26897 non-null  object
 1   tv            26897 non-null  object
 2   year          26897 non-null  int64
 3   rating        13112 non-null  object
 4   score_imdb    24921 non-null  float64
 5   score_rotten  8148 non-null   object
 6   link          26897 non-null  object
 7   available_on  26897 non-null  object
 8   country       10916 non-null  object
 9   decade        26897 non-null  int64
 10  genres        25065 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 2.5+ MB

In [67]:
df_all_data2.to_csv('../data/df_all_data2.csv')

### Files then updated and renamed once making sure Tableau connection updated correctly.

Final file with all genres populated is back as df_all_data